// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOqfhWGbLvBxboy_XY3wAO_MlVO88p_rc',
    appId: '1:18686812898:web:a74ffd05806c181f4674bb',
    messagingSenderId: '18686812898',
    projectId: 'tlcapp-1664a',
    authDomain: 'tlcapp-1664a.firebaseapp.com',
    storageBucket: 'tlcapp-1664a.firebasestorage.app',
    measurementId: 'G-DWRZGZD1E9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWiGiI-jRT9w1tmq8uE2je66A2nRidRIU',
    appId: '1:18686812898:android:55989f38fd4c8abf4674bb',
    messagingSenderId: '18686812898',
    projectId: 'tlcapp-1664a',
    storageBucket: 'tlcapp-1664a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsQZ0c0xnncW8kfN8C3_2S2HjMTlG3G0k',
    appId: '1:18686812898:ios:027d3338b74cbdda4674bb',
    messagingSenderId: '18686812898',
    projectId: 'tlcapp-1664a',
    storageBucket: 'tlcapp-1664a.firebasestorage.app',
    iosBundleId: 'com.example.tlcNyc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsQZ0c0xnncW8kfN8C3_2S2HjMTlG3G0k',
    appId: '1:18686812898:ios:027d3338b74cbdda4674bb',
    messagingSenderId: '18686812898',
    projectId: 'tlcapp-1664a',
    storageBucket: 'tlcapp-1664a.firebasestorage.app',
    iosBundleId: 'com.example.tlcNyc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOqfhWGbLvBxboy_XY3wAO_MlVO88p_rc',
    appId: '1:18686812898:web:c6e9b4f392f70ac34674bb',
    messagingSenderId: '18686812898',
    projectId: 'tlcapp-1664a',
    authDomain: 'tlcapp-1664a.firebaseapp.com',
    storageBucket: 'tlcapp-1664a.firebasestorage.app',
    measurementId: 'G-NCY9W2XWT0',
  );
}
